/**
 * ClipboardMonitor
 *
 * Polls the system clipboard for new text content.
 * Dedup: skips if text matches the last captured value.
 * ConcealedType / AutoGeneratedType detection: skipped entries are not captured.
 *
 * NOTE: Actual NSPasteboard access requires Electron main process.
 * For now we use the electron clipboard module as a placeholder.
 * Native Swift bridge integration will come in a later phase.
 */

import type { ClipboardEntry, ClipboardMonitorConfig } from './types';

const DEFAULT_POLL_INTERVAL_MS = 500;

/**
 * Abstraction over clipboard access for testability.
 * Production code injects the real electron clipboard;
 * tests inject a mock.
 */
export interface ClipboardAdapter {
  readText(): string;
  /** Returns true if the current clipboard item has a concealed type. */
  isConcealedType(): boolean;
  /** Returns true if the current clipboard item is auto-generated. */
  isAutoGeneratedType(): boolean;
}

export class ClipboardMonitor {
  private intervalId: ReturnType<typeof setInterval> | null = null;
  private lastCapturedText: string | null = null;
  private readonly adapter: ClipboardAdapter;

  constructor(adapter: ClipboardAdapter) {
    this.adapter = adapter;
  }

  /** Begin polling the clipboard at the configured interval. */
  start(config: ClipboardMonitorConfig): void {
    if (this.intervalId !== null) {
      return; // Already running
    }

    const intervalMs = config.pollIntervalMs > 0
      ? config.pollIntervalMs
      : DEFAULT_POLL_INTERVAL_MS;

    this.intervalId = setInterval(() => {
      this.poll(config.onCapture);
    }, intervalMs);
  }

  /** Stop polling the clipboard. */
  stop(): void {
    if (this.intervalId !== null) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }

  /** Returns true if the monitor is currently polling. */
  isRunning(): boolean {
    return this.intervalId !== null;
  }

  private poll(onCapture: (entry: ClipboardEntry) => void): void {
    try {
      const text = this.adapter.readText();

      if (!text) {
        return;
      }

      // Dedup: skip if same as last capture
      if (text === this.lastCapturedText) {
        return;
      }

      // Skip concealed types (e.g., password managers)
      if (this.adapter.isConcealedType()) {
        return;
      }

      // Skip auto-generated types
      if (this.adapter.isAutoGeneratedType()) {
        return;
      }

      this.lastCapturedText = text;

      const entry: ClipboardEntry = {
        text,
        timestamp: new Date().toISOString(),
        concealed: false,
      };

      onCapture(entry);
    } catch (error: unknown) {
      // Clipboard access can fail silently (e.g., permissions).
      // We log but do not propagate to avoid crashing the poll loop.
      const message =
        error instanceof Error ? error.message : 'Unknown clipboard error';
      console.error(`[ClipboardMonitor] Poll error: ${message}`);
    }
  }
}
