import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { ClipboardMonitor } from './clipboard-monitor';
import type { ClipboardAdapter } from './clipboard-monitor';
import type { ClipboardEntry, ClipboardMonitorConfig } from './types';

function createMockAdapter(overrides?: Partial<ClipboardAdapter>): ClipboardAdapter {
  return {
    readText: vi.fn().mockReturnValue(''),
    isConcealedType: vi.fn().mockReturnValue(false),
    isAutoGeneratedType: vi.fn().mockReturnValue(false),
    ...overrides,
  };
}

describe('ClipboardMonitor', () => {
  let monitor: ClipboardMonitor;
  let adapter: ClipboardAdapter;

  beforeEach(() => {
    vi.useFakeTimers();
    adapter = createMockAdapter();
    monitor = new ClipboardMonitor(adapter);
  });

  afterEach(() => {
    monitor.stop();
    vi.useRealTimers();
  });

  describe('start / stop lifecycle', () => {
    it('is not running initially', () => {
      expect(monitor.isRunning()).toBe(false);
    });

    it('is running after start', () => {
      const config: ClipboardMonitorConfig = {
        pollIntervalMs: 100,
        onCapture: vi.fn(),
      };

      monitor.start(config);

      expect(monitor.isRunning()).toBe(true);
    });

    it('is not running after stop', () => {
      const config: ClipboardMonitorConfig = {
        pollIntervalMs: 100,
        onCapture: vi.fn(),
      };

      monitor.start(config);
      monitor.stop();

      expect(monitor.isRunning()).toBe(false);
    });

    it('does not double-start if already running', () => {
      const onCapture = vi.fn();
      const config: ClipboardMonitorConfig = {
        pollIntervalMs: 100,
        onCapture,
      };

      monitor.start(config);
      monitor.start(config); // Second call should be no-op

      expect(monitor.isRunning()).toBe(true);
    });

    it('stop is safe to call when not running', () => {
      expect(() => monitor.stop()).not.toThrow();
    });
  });

  describe('capturing clipboard content', () => {
    it('captures new clipboard content', () => {
      const onCapture = vi.fn();
      (adapter.readText as ReturnType<typeof vi.fn>).mockReturnValue('Hello clipboard');

      monitor.start({ pollIntervalMs: 100, onCapture });
      vi.advanceTimersByTime(100);

      expect(onCapture).toHaveBeenCalledTimes(1);
      const entry: ClipboardEntry = onCapture.mock.calls[0][0];
      expect(entry.text).toBe('Hello clipboard');
      expect(entry.concealed).toBe(false);
      expect(entry.timestamp).toBeTruthy();
    });

    it('captures multiple different entries', () => {
      const onCapture = vi.fn();
      const readText = adapter.readText as ReturnType<typeof vi.fn>;
      readText.mockReturnValue('First');

      monitor.start({ pollIntervalMs: 100, onCapture });
      vi.advanceTimersByTime(100);

      readText.mockReturnValue('Second');
      vi.advanceTimersByTime(100);

      expect(onCapture).toHaveBeenCalledTimes(2);
      expect(onCapture.mock.calls[0][0].text).toBe('First');
      expect(onCapture.mock.calls[1][0].text).toBe('Second');
    });

    it('does not capture empty clipboard', () => {
      const onCapture = vi.fn();
      (adapter.readText as ReturnType<typeof vi.fn>).mockReturnValue('');

      monitor.start({ pollIntervalMs: 100, onCapture });
      vi.advanceTimersByTime(100);

      expect(onCapture).not.toHaveBeenCalled();
    });
  });

  describe('dedup', () => {
    it('does not capture same content twice', () => {
      const onCapture = vi.fn();
      (adapter.readText as ReturnType<typeof vi.fn>).mockReturnValue('Same text');

      monitor.start({ pollIntervalMs: 100, onCapture });
      vi.advanceTimersByTime(100); // First capture
      vi.advanceTimersByTime(100); // Should be deduped
      vi.advanceTimersByTime(100); // Should be deduped

      expect(onCapture).toHaveBeenCalledTimes(1);
    });

    it('captures again after content changes and changes back', () => {
      const onCapture = vi.fn();
      const readText = adapter.readText as ReturnType<typeof vi.fn>;
      readText.mockReturnValue('First');

      monitor.start({ pollIntervalMs: 100, onCapture });
      vi.advanceTimersByTime(100); // Capture "First"

      readText.mockReturnValue('Second');
      vi.advanceTimersByTime(100); // Capture "Second"

      readText.mockReturnValue('First');
      vi.advanceTimersByTime(100); // Capture "First" again (different from last)

      expect(onCapture).toHaveBeenCalledTimes(3);
    });
  });

  describe('concealed type detection', () => {
    it('skips concealed clipboard items', () => {
      const onCapture = vi.fn();
      (adapter.readText as ReturnType<typeof vi.fn>).mockReturnValue('secret-password');
      (adapter.isConcealedType as ReturnType<typeof vi.fn>).mockReturnValue(true);

      monitor.start({ pollIntervalMs: 100, onCapture });
      vi.advanceTimersByTime(100);

      expect(onCapture).not.toHaveBeenCalled();
    });

    it('skips auto-generated clipboard items', () => {
      const onCapture = vi.fn();
      (adapter.readText as ReturnType<typeof vi.fn>).mockReturnValue('auto-gen-content');
      (adapter.isAutoGeneratedType as ReturnType<typeof vi.fn>).mockReturnValue(true);

      monitor.start({ pollIntervalMs: 100, onCapture });
      vi.advanceTimersByTime(100);

      expect(onCapture).not.toHaveBeenCalled();
    });

    it('captures normal items when concealed check returns false', () => {
      const onCapture = vi.fn();
      (adapter.readText as ReturnType<typeof vi.fn>).mockReturnValue('normal text');
      (adapter.isConcealedType as ReturnType<typeof vi.fn>).mockReturnValue(false);
      (adapter.isAutoGeneratedType as ReturnType<typeof vi.fn>).mockReturnValue(false);

      monitor.start({ pollIntervalMs: 100, onCapture });
      vi.advanceTimersByTime(100);

      expect(onCapture).toHaveBeenCalledTimes(1);
    });
  });

  describe('callback shape', () => {
    it('calls onCapture with correct ClipboardEntry shape', () => {
      const onCapture = vi.fn();
      (adapter.readText as ReturnType<typeof vi.fn>).mockReturnValue('Test text');

      monitor.start({ pollIntervalMs: 100, onCapture });
      vi.advanceTimersByTime(100);

      expect(onCapture).toHaveBeenCalledTimes(1);
      const entry: ClipboardEntry = onCapture.mock.calls[0][0];

      expect(entry).toHaveProperty('text', 'Test text');
      expect(entry).toHaveProperty('concealed', false);
      expect(entry).toHaveProperty('timestamp');
      // Verify ISO 8601 format
      expect(() => new Date(entry.timestamp)).not.toThrow();
      expect(new Date(entry.timestamp).toISOString()).toBe(entry.timestamp);
    });
  });

  describe('error handling', () => {
    it('continues polling after adapter error', () => {
      const onCapture = vi.fn();
      const readText = adapter.readText as ReturnType<typeof vi.fn>;
      const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

      readText.mockImplementationOnce(() => {
        throw new Error('Permission denied');
      });

      monitor.start({ pollIntervalMs: 100, onCapture });
      vi.advanceTimersByTime(100); // Error on first poll

      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining('Permission denied')
      );

      // Monitor should still be running
      readText.mockReturnValue('Recovered');
      vi.advanceTimersByTime(100);

      expect(onCapture).toHaveBeenCalledTimes(1);
      expect(onCapture.mock.calls[0][0].text).toBe('Recovered');

      consoleSpy.mockRestore();
    });
  });

  describe('poll interval', () => {
    it('uses configured poll interval', () => {
      const onCapture = vi.fn();
      (adapter.readText as ReturnType<typeof vi.fn>).mockReturnValue('text');

      monitor.start({ pollIntervalMs: 250, onCapture });

      vi.advanceTimersByTime(200);
      expect(onCapture).not.toHaveBeenCalled();

      vi.advanceTimersByTime(50);
      expect(onCapture).toHaveBeenCalledTimes(1);
    });

    it('falls back to default interval for non-positive values', () => {
      const onCapture = vi.fn();
      (adapter.readText as ReturnType<typeof vi.fn>).mockReturnValue('text');

      monitor.start({ pollIntervalMs: 0, onCapture });

      // Default is 500ms
      vi.advanceTimersByTime(499);
      expect(onCapture).not.toHaveBeenCalled();

      vi.advanceTimersByTime(1);
      expect(onCapture).toHaveBeenCalledTimes(1);
    });
  });
});
